name: Release

on:
  push:
    branches:
      - main
permissions: {}
jobs:
  release:
    if: github.repository == 'mikededo/dart-barrel-file-generator'
    permissions:
      contents: write # to create release
      pull-requests: write # to create pull request (changesets/action)
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install
        run: bun install --frozen-lockfile
      - name: Capture new release versions
        run: |
          bun changeset status --output=release.json
          echo "CHANGED_PACKAGES=$(jq -r '.releases | map(.name + "@" + .newVersion) | join(", ")' release.json)" >> "$GITHUB_ENV"
          rm release.json
      - name: Create PR release or publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: bun changeset version
          publish: ./release.sh
          commit: 'chore(release): ${{env.CHANGED_PACKAGES}}'
          title: 'chore(release): ${{env.CHANGED_PACKAGES}}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
